### ISSUE TITLE
any suggestions for fuzzy search?

### ISSUE THREAD

**Issue by lingjiawen** [H5GG/H5GG#39]
how can i do a fuzzy search? such as increase, discrease, no change?

**Comment by lingjiawen** [comment]
Seems like iGameGod/iGameGuardian/iMemEditor can not do a range search such as -2000~-1000, i would like to finish this feat using h5gg,  any suggestions for this?
btw, Range Search in h5gg don't support from negative to positive, for example, -1~1 is not support till now.

**Comment by lingjiawen** [comment]
thanks a lot

**Comment by Happy-Secret** [comment]
> range search fixed. and h5gg is not design for fuzzy search.

What do you mean by fixed? There is a new version of H5GG after 7.9?
