### ISSUE TITLE
H5 string search, help me.

### ISSUE THREAD

**Issue by lyjprint** [H5GG/H5GG#43]
Why can't I find the string? The result is 0.

**Comment by lyjprint** [comment]
function readUTF32String(address, maxlen)
{
    var str = "server";

    for (var s = 0; !maxlen||s<maxlen; s++) {
        var charCode = Number(h5gg.getValue(address + s * 4, "I32"));

        if(!charCode) break;
        str += String.fromCharCode(charCode);
    }

return str;
    
}

**Comment by Happy-Secret** [comment]
I have achieve it with Frida Memory.Scan.
You may find it here (through H5Frida)
https://iosgods.com/topic/169517-h5gg-script-menu-to-read-write-live-arm64-instruction-on-an-address-work-on-non-jailbroken/
