### ISSUE TITLE
Crash when call patched offset in unity framework

### ISSUE THREAD

**Issue by HaidarPhantom** [H5GG/H5GG#59]
it always crashes for me for some reason.!!

in my game im patching the offset of it with C0***FD6 (ret) only! maybe because the script doesnt support like this way?
my script is 
ActiveCodePatch("Frameworks/UnityFramework.framework/UnityFramework", 0x259BC62, "C0035FD6");
if i patched unity framework from ida the patch work perfectly but in H5GG and your method it failed
not crash at launch. but it crashes with the location of my patch it self
i tried it on 16.2

and 14.8 jailbroken and it is the same issue.

i tried 2 games btw
this is my h5frida-code-patch-test(non-jailbreak).js Script.
is there something wrong with it?
````
h5gg.require(7.9);
var h5frida=h5gg.loadPlugin("h5frida", "h5frida-15.1.24.dylib");
if(!h5frida) throw "Failed to load h5frida plugin";

function ActiveCodePatch(fpath, vaddr, bytes) {
    if(!h5frida.ActiveCodePatch(fpath, vaddr, bytes)) {
        var result = h5frida.ApplyCodePatch(fpath, vaddr, bytes);
        alert(fpath+":0x"+vaddr.toString(16)+"-修改失败!\n" + fpath+":0x"+vaddr.toString(16)+"-PatchFailed!\n" + result);return false;
    } return true;
}
function DeactiveCodePatch(fpath, vaddr, bytes) {
    return h5frida.DeactiveCodePatch(fpath, vaddr, bytes);
}

ActiveCodePatch("Frameworks/UnityFramework.framework/UnityFramework", 0x2XXXX62, "C0XXXD6");
ActiveCodePatch("Frameworks/UnityFramework.framework/UnityFramework", 0x259XXXD, "C0XXXD6");
ActiveCodePatch("Frameworks/UnityFramework.framework/UnityFramework", 0x25XXX56, "C00XXXD6");
ActiveCodePatch("Frameworks/UnityFramework.framework/UnityFramework", 0x25XXXX6, "C00XXXD6");`
```

**Comment by HaidarPhantom** [comment]
this is the full patch 
```
ActiveCodePatch("Frameworks/UnityFramework.framework/UnityFramework", 0x2598962, "C0035FD6");
ActiveCodePatch("Frameworks/UnityFramework.framework/UnityFramework", 0x2599ABD, "C0035FD6");
ActiveCodePatch("Frameworks/UnityFramework.framework/UnityFramework", 0x2599B56, "C0035FD6");
ActiveCodePatch("Frameworks/UnityFramework.framework/UnityFramework", 0x25A1BD6, "C0035FD6");
```
what do you mean align to 4 ?
because they are different offsets

**Comment by HaidarPhantom** [comment]
i just have to edit the highlited
could you tell me what to do?
because i have no ida how to align with 4 bytes.
<img width="212" alt="Screen Shot 2023-04-07 at 10 38 30 AM" src="https://user-images.githubusercontent.com/17025148/230564733-054e7232-222a-46ff-abb6-9b6acccac5d3.png">

**Comment by HaidarPhantom** [comment]
i just have to edit the highlited
could you tell me what to do?
because i have no ida how to align with 4 bytes.
<img width="212" alt="Screen Shot 2023-04-07 at 10 38 30 AM" src="https://user-images.githubusercontent.com/17025148/230564998-5721c07e-bb16-4f80-8693-e911e0305437.png">

**Comment by HaidarPhantom** [comment]
<img width="212" alt="Screen Shot 2023-04-07 at 10 38 30 AM" src="https://user-images.githubusercontent.com/17025148/230565068-b00ba074-12f9-4981-a54c-5d12d09d9a74.png">
i have no ida how to align to 4 byte
could you be more detaied?
in ida i just edit this highlighted offset with C0035FD6 and it is done.
how to do it in H5GG 
https://user-images.githubusercontent.com/17025148/230565068-b00ba074-12f9-4981-a54c-5d12d09d9a74.png

**Comment by silentninjabee** [comment]
on iOS and ARM64 architecture functions are usually aligned to 4byte bounds in memory, the alignment means that the starting address of a function is a multiple of 4.

Also your address in IDA is not the same as your runtime address, you need to add the base address before you patch anything

**Comment by Happy-Secret** [comment]
> <img alt="Screen Shot 2023-04-07 at 10 38 30 AM" width="212" src="https://user-images.githubusercontent.com/17025148/230565068-b00ba074-12f9-4981-a54c-5d12d09d9a74.png">
> 
> i have no ida how to align to 4 byte could you be more detaied? in ida i just edit this highlighted offset with C0035FD6 and it is done. how to do it in H5GG https://user-images.githubusercontent.com/17025148/230565068-b00ba074-12f9-4981-a54c-5d12d09d9a74.png

In this case, your offset is 0x2598960

**Comment by HaidarPhantom** [comment]
i figured out how to fix it.
thank you all for the help.
i will close the issue because it has been solved
